// <auto-generated />
using System;
using CurriBackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CurriBackendApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904160350_AddAdminUsers")]
    partial class AddAdminUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CurriBackendApi.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admin_users");
                });

            modelBuilder.Entity("CurriBackendApi.Models.Educacion", b =>
                {
                    b.Property<int>("Id_Edu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Edu"));

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Institución")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo_Obtenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Edu");

                    b.ToTable("educación");
                });

            modelBuilder.Entity("CurriBackendApi.Models.Experiencialaboral", b =>
                {
                    b.Property<int>("Id_Expe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Expe"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Experiencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaIni")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("integer");

                    b.HasKey("Id_Expe");

                    b.ToTable("experiencia_laboral");
                });

            modelBuilder.Entity("CurriBackendApi.Models.Habilidad", b =>
                {
                    b.Property<int>("Id_tecnologia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_tecnologia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_tecnologia"));

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_tecnologia");

                    b.ToTable("tecnologias");
                });

            modelBuilder.Entity("CurriBackendApi.Models.Usuarios", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("AcercaDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedinUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TituloProfesional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_Usuario");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
